version: "3"
services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    ports:
      - 4873:4873
    networks:
      - default

  echidna:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default

    volumes:
      - .:/workspace

      # Avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

      # Forward the local Docker socket to the container
      - /var/run/docker.sock:/var/run/docker.sock

    working_dir: /workspace

    # Override default command so things don't shut down after the process ends
    command: sleep infinity

networks:
  default:
    driver: bridge
