version: "3"
services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    ports:
      - 4873:4873
    networks:
      - default

  release:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    volumes:
      - .:/workspace
    working_dir: /workspace

networks:
  default:
    driver: bridge
